### ISSUE TITLE
Panes are merged when moving with "Ctrl"

### ISSUE THREAD

**Issue by steakhutzeee** [hiasr/vim-zellij-navigator#11]
Hi, noted a thing with the plugin.

Let's say I have a layout like this:

![1](https://github.com/hiasr/vim-zellij-navigator/assets/57228102/2588f35d-b5c7-4a74-868e-6ea4cf099f0c)

I can move without any issues with the default (so not related to the plugin) keys "Alt + arrow keys".

But if with this layout I use the plugin to move and hit "Ctrl + h" then this happens:

![2](https://github.com/hiasr/vim-zellij-navigator/assets/57228102/98485d08-e8a8-4ad3-9427-1fe815a4697c)

Oddly this also happens if in the situation of the first picture I hit "Ctrl + j" or "Ctrl + k".

What could be the cause?

**Comment by steakhutzeee** [comment]
This does not happen if opening Zellij I hit in a series of combination all the keys "Ctrl + hjkl". I see something flashing and setting the plugin on screen, very briefly, and after that it works.

Could this be fixed somehow?

**Comment by hiasr** [comment]
That is indeed very weird, could you send your full config? The behaviour seems to be the same as the Alt+][ keybindings.

**Comment by steakhutzeee** [comment]
Basically I have to hit all the combinations when I open Zellij, like if it needs to load all the plugin variants. After that it works.

My config https://gist.github.com/steakhutzeee/f88fd14bc4f8a39f569c758b417df08b

**Comment by hiasr** [comment]
I think this was a Zellij thing that has been fixed in the meantime. I just tried with your config and didn't have any issues. Feel free to reopen should you encounter it again!
