### ISSUE TITLE
"move_focus_or_tab" not working if Neovim is running alone 

### ISSUE THREAD

**Issue by steakhutzeee** [hiasr/vim-zellij-navigator#12]
Hi,

noted that `move_focus_or_tab` does not work if Neovim is the only thing running in a pane, so it does not switch to other tabs. This only works outstide of Neovim.

Could be possible to extend this functionality to let it work in this scenario? 

Thanks!

**Comment by hiasr** [comment]
Which companion plugin are you using in Neovim? Under the hood we forward all keystrokes to neovim if that's the focused application. This means it is up to the Neovim plugin to execute that command.

**Comment by steakhutzeee** [comment]
Using [zellij-nav.nvim](https://github.com/swaits/zellij-nav.nvim)

**Comment by Peeeaje** [comment]
@steakhutzeee 
I guess it's caused because the plugin is not using move_focus_or_tab in its implementation.

I forked that and enable move_focus_or_tab for left/right move so try it if you want.
https://github.com/Peeeaje/zellij-nav.nvim

@hiasr 
If you don't mind could you replace the plugin in the readme?

**Comment by allpan3** [comment]
> Unfortunately I’m unable to reproduce as I moved to https://github.com/fresh2dev/zellij-autolock and its Nvim plugin.
@steakhutzeee Were you able to get MoveFocusOrTab to work with autolock though? I'm still facing the same issue.

**Comment by steakhutzeee** [comment]
> > Unfortunately I’m unable to reproduce as I moved to https://github.com/fresh2dev/zellij-autolock and its Nvim plugin.
> > @steakhutzeee Were you able to get MoveFocusOrTab to work with autolock though? I'm still facing the same issue.

Hi, unfortunately no, it looks that the feature is not present. Above you can see a feature request I issued for it.

**Comment by hiasr** [comment]
Hi, I will be closing this since this is a feature that must be implemented in a corresponding Neovim plugin.

It seems zellij-nav.nvim currently has a [PR open](https://github.com/swaits/zellij-nav.nvim/pull/4) for exactly this.
Let me know if it still doesn't work!
