### ISSUE TITLE
It does not move across tabs.

### ISSUE THREAD

**Issue by Peeeaje** [hiasr/vim-zellij-navigator#2]
I tried this plugin and it is great in general, thanks.

I don't know if this is bug or still under development but when I am on the edge of pane and try to go to next tab, it does not move to next tab.
It might be possible by using `move_focus_or_tab` instead of `move_focus` but I haven't tried.

**Comment by hiasr** [comment]
Fixed with [this commit](https://github.com/hiasr/vim-zellij-navigator/commit/6dfb8c634de4478f9a1952700bce984ead3c8e5d). Will be included in the new release in one of the coming days!

**Comment by Peeeaje** [comment]
Thanks!!
