### ISSUE TITLE
Feature request: Allow more messages

### ISSUE THREAD

**Issue by andresatierf** [hiasr/vim-zellij-navigator#4]
Hey, love your work. I can finally move from tmux into zellij thanks to you.

This is kind of a 2 part request. 
1. Allow more messages:
    - [ ] "resize"
    - [ ] "move_focus_or_tab"
2. the current "move_focus" should not default to "move_focus_or_tab" for left and right movements.

Let me know if this is something you intend to implement

**Comment by hiasr** [comment]
Both are something I will implement in the near future. I intend to keep the move_focus_or_tab as the default since this is also the case in the default Zellij config. However, I will add the possibility to disable this

**Comment by hiasr** [comment]
I just reread your comment, I think providing separate actions for move_focus and move_focus_or_tab is a good idea. I will do it that way.

**Comment by hiasr** [comment]
Both added in 0.2.1, let me know if you still have issues!
