### ISSUE TITLE
No possible to switch from a pane with instance of vim/nvim that is suspended by Ctrl+Z

### ISSUE THREAD

**Issue by askobara** [hiasr/vim-zellij-navigator#8]
I'm not sure that is a problem inside your plugin, or even zellij itself. Because I can't reproduce this behavior with other "full-pane" applications (nano, less).

But maybe you have any idea what is going wrong.

**Comment by hiasr** [comment]
I don't think I fully understand your problem. What do you mean by "suspended by Ctrl+z", this is not a default keybinding in Zellij. Could you write down the steps to reproduce your problem and the expected behaviour?

**Comment by askobara** [comment]
My bad.

To reproduce this you'll need 2 panes, **left** and **right** for example. Within the left pane run an instance of vim/nvim, once it's initialized press Ctrl+Z to suspend it -- control will returns to the shell. Now, if I'm trying to move to the right pane I'll get two different results according to Ctrl or Alt based config: cleaning of the pane, with Ctrl-based config (default behavior of a terminal), or displaying the output of the current directory (as like after ls command 🤯) with Alt-based.

I've tried this in alacritty and gnome-terminal.

**Comment by hiasr** [comment]
I managed to reproduce this. The issue is that when Neovim is suspended, Zellij still lists neovim as the active command as long as no other command is running at that point in time. It is a valid point, I will raise it with Zellij, but little I can do on my side to resolve this.

**Comment by askobara** [comment]
Wow! That was brilliant! I didn't even try to check the list of clients
