### ISSUE TITLE
Plugin not works when in nvim pane

### ISSUE THREAD

**Issue by steakhutzeee** [hiasr/vim-zellij-navigator#9]
Hi, thank you for your plugin :)

So I first had to remap:

```
    shared_except "move" "locked" {
        bind "Ctrl m" { SwitchToMode "Move"; }
    }
```
as it was already used by `Ctlr h`

Secondly I installed https://github.com/swaits/zellij-nav.nvim by adding the following in `zellij-nav.lua`:

```
local M = {
  "https://git.sr.ht/~swaits/zellij-nav.nvim",
  lazy = true,
  event = "VeryLazy",
  keys = {
    { "<c-h>", "<cmd>ZellijNavigateLeft<cr>",  { silent = true, desc = "navigate left"  } },
    { "<c-j>", "<cmd>ZellijNavigateDown<cr>",  { silent = true, desc = "navigate down"  } },
    { "<c-k>", "<cmd>ZellijNavigateUp<cr>",    { silent = true, desc = "navigate up"    } },
    { "<c-l>", "<cmd>ZellijNavigateRight<cr>", { silent = true, desc = "navigate right" } },
  },
}

M.config = function()
  require("zellij-nav").setup {}
end

return M
```
and the following https://github.com/hiasr/vim-zellij-navigator?tab=readme-ov-file#usage to my zellij config.

The first time I tried to move to another pane, zellij asked for permissions.

This actually works, I see the the screen flashing when moving and I can actually move between panes. But when I go into a pane running nvim then I'm locked there. I try to move, the screen flashes but the action is not completed. I'm still in the nvim pane.

Any idea why?

**Comment by steakhutzeee** [comment]
It looks the issue is I'm actually also using https://github.com/christoomey/vim-tmux-navigator :D

Disabling it looks like working.

**Comment by hiasr** [comment]
Glad you figured it out!
